# Generated by Django 3.0.1 on 2019-12-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0015_auto_20191027_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='job_id',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
